In [2]:
import os

In [3]:
print(os.listdir())

['.ipynb_checkpoints', '.project', '10. Excel_ IBD_Demo.xlsx', '10. Excel_ SoftDrink_QL_tabulation.xls', '10.2 lab data sets.xlsx', '10.2 Lab exercise.docx', '10.Excel _Marathon- Stem and leaf.xlsx', '10.Excel _TVMedia_ Tabulation.xls', '10.Excel_ Smartphone usage_freq& SL.xlsx', 'Assignment 1.docx', 'B10IMNrmlznEx3.pdf', 'Banking Data.xlsx', 'base ball player data set.xls', 'Blank Package.emx', 'Cell Phone Survey.xlsx', 'Command Editor.lnk', 'Consumer_Complaints.csv', 'Data Base explanation_Ver1.docx', 'Data base.xlsx', 'DecisionTree Project.ipynb', 'DecisionTree.txt', 'desktop.ini', 'Doc_01.docx', 'employees.csv', 'Facebook Survey.xlsx', 'fwd10thbatchpgcba_day1_practise.zip', 'groupStudy.csv', 'HeartRate.xls', 'heps', 'HousingData.csv', 'KNN.txt', 'LinearRegressionProject.ipynb', 'loanData.csv', 'LR.txt', 'MachineLearning', 'NAIVE BAYES.txt', 'New Car Sales.xlsx', 'Non invasive BGM.docx', 'Practice.ipynb', 'prasanna.txt', 'Pras_logistics.emx', 'PROSTHETIC HAND CONTROL VIA BLUETOOTH.docx', 'rishi222.ipynb', 'S0IntroductionToBusinessAnalytics.pdf', 'S1ShortIntroductionToBigData.pdf', 'S2DIKInfoSys.pdf', 'S3FileSystem.pdf', 'S4IntroToDBS.pdf', 'S5DatabaseModel.pdf', 'S6EntityAndAttribute.pdf', 'S7EntityRelationshipModel.pdf', 'S8BasicsOfNormalization.pdf', 'S9DBNormalization.pdf', 'Social_Network_Ads.csv', 'Spyder.lnk', 'Sql ex 8.txt', 'SQL Exercise queries.docx', 'SQL queries exercise - mukesh.txt', 'SupportVectorMachine Project.ipynb', 'SVM.txt', 'tables', 'test.txt', 'test1.txt', 'test2.txt', 'Udemy.Python.for.Data.Science.and.Machine.Learning.Bootcamp_p30download.com', 'WorkWithFiles.py', 'www.TamilRockers.re - Arjun Reddy (2017) Telugu HDRip x264 700MB ESubs.mkv']

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
import matplotlib.pyplot as plt

In [7]:
%matplotlib inline

In [8]:
data=pd.read_csv('Social_Network_Ads.csv')

In [9]:
data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB

In [11]:
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [12]:
data.tail()

      User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [13]:
data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [14]:
X=data.iloc[:,[2,3]].values

In [15]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],
       [    27,  58000],
       [    24,  55000],
       [    23,  48000],
       [    28,  79000],
       [    22,  18000],
       [    32, 117000],
       [    27,  20000],
       [    25,  87000],
       [    23,  66000],
       [    32, 120000],
       [    59,  83000],
       [    24,  58000],
       [    24,  19000],
       [    23,  82000],
       [    22,  63000],
       [    31,  68000],
       [    25,  80000],
       [    24,  27000],
       [    20,  23000],
       [    33, 113000],
       [    32,  18000],
       [    34, 112000],
       [    18,  52000],
       [    22,  27000],
       [    28,  87000],
       [    26,  17000],
       [    30,  80000],
       [    39,  42000],
       [    20,  49000],
       [    35,  88000],
       [    30,  62000],
       [    31, 118000],
       [    24,  55000],
       [    28,  85000],
       [    26,  81000],
       [    35,  50000],
       [    22,  81000],
       [    30, 116000],
       [    26,  15000],
       [    29,  28000],
       [    29,  83000],
       [    35,  44000],
       [    35,  25000],
       [    28, 123000],
       [    35,  73000],
       [    28,  37000],
       [    27,  88000],
       [    28,  59000],
       [    32,  86000],
       [    33, 149000],
       [    19,  21000],
       [    21,  72000],
       [    26,  35000],
       [    27,  89000],
       [    26,  86000],
       [    38,  80000],
       [    39,  71000],
       [    37,  71000],
       [    38,  61000],
       [    37,  55000],
       [    42,  80000],
       [    40,  57000],
       [    35,  75000],
       [    36,  52000],
       [    40,  59000],
       [    41,  59000],
       [    36,  75000],
       [    37,  72000],
       [    40,  75000],
       [    35,  53000],
       [    41,  51000],
       [    39,  61000],
       [    42,  65000],
       [    26,  32000],
       [    30,  17000],
       [    26,  84000],
       [    31,  58000],
       [    33,  31000],
       [    30,  87000],
       [    21,  68000],
       [    28,  55000],
       [    23,  63000],
       [    20,  82000],
       [    30, 107000],
       [    28,  59000],
       [    19,  25000],
       [    19,  85000],
       [    18,  68000],
       [    35,  59000],
       [    30,  89000],
       [    34,  25000],
       [    24,  89000],
       [    27,  96000],
       [    41,  30000],
       [    29,  61000],
       [    20,  74000],
       [    26,  15000],
       [    41,  45000],
       [    31,  76000],
       [    36,  50000],
       [    40,  47000],
       [    31,  15000],
       [    46,  59000],
       [    29,  75000],
       [    26,  30000],
       [    32, 135000],
       [    32, 100000],
       [    25,  90000],
       [    37,  33000],
       [    35,  38000],
       [    33,  69000],
       [    18,  86000],
       [    22,  55000],
       [    35,  71000],
       [    29, 148000],
       [    29,  47000],
       [    21,  88000],
       [    34, 115000],
       [    26, 118000],
       [    34,  43000],
       [    34,  72000],
       [    23,  28000],
       [    35,  47000],
       [    25,  22000],
       [    24,  23000],
       [    31,  34000],
       [    26,  16000],
       [    31,  71000],
       [    32, 117000],
       [    33,  43000],
       [    33,  60000],
       [    31,  66000],
       [    20,  82000],
       [    33,  41000],
       [    35,  72000],
       [    28,  32000],
       [    24,  84000],
       [    19,  26000],
       [    29,  43000],
       [    19,  70000],
       [    28,  89000],
       [    34,  43000],
       [    30,  79000],
       [    20,  36000],
       [    26,  80000],
       [    35,  22000],
       [    35,  39000],
       [    49,  74000],
       [    39, 134000],
       [    41,  71000],
       [    58, 101000],
       [    47,  47000],
       [    55, 130000],
       [    52, 114000],
       [    40, 142000],
       [    46,  22000],
       [    48,  96000],
       [    52, 150000],
       [    59,  42000],
       [    35,  58000],
       [    47,  43000],
       [    60, 108000],
       [    49,  65000],
       [    40,  78000],
       [    46,  96000],
       [    59, 143000],
       [    41,  80000],
       [    35,  91000],
       [    37, 144000],
       [    60, 102000],
       [    35,  60000],
       [    37,  53000],
       [    36, 126000],
       [    56, 133000],
       [    40,  72000],
       [    42,  80000],
       [    35, 147000],
       [    39,  42000],
       [    40, 107000],
       [    49,  86000],
       [    38, 112000],
       [    46,  79000],
       [    40,  57000],
       [    37,  80000],
       [    46,  82000],
       [    53, 143000],
       [    42, 149000],
       [    38,  59000],
       [    50,  88000],
       [    56, 104000],
       [    41,  72000],
       [    51, 146000],
       [    35,  50000],
       [    57, 122000],
       [    41,  52000],
       [    35,  97000],
       [    44,  39000],
       [    37,  52000],
       [    48, 134000],
       [    37, 146000],
       [    50,  44000],
       [    52,  90000],
       [    41,  72000],
       [    40,  57000],
       [    58,  95000],
       [    45, 131000],
       [    35,  77000],
       [    36, 144000],
       [    55, 125000],
       [    35,  72000],
       [    48,  90000],
       [    42, 108000],
       [    40,  75000],
       [    37,  74000],
       [    47, 144000],
       [    40,  61000],
       [    43, 133000],
       [    59,  76000],
       [    60,  42000],
       [    39, 106000],
       [    57,  26000],
       [    57,  74000],
       [    38,  71000],
       [    49,  88000],
       [    52,  38000],
       [    50,  36000],
       [    59,  88000],
       [    35,  61000],
       [    37,  70000],
       [    52,  21000],
       [    48, 141000],
       [    37,  93000],
       [    37,  62000],
       [    48, 138000],
       [    41,  79000],
       [    37,  78000],
       [    39, 134000],
       [    49,  89000],
       [    55,  39000],
       [    37,  77000],
       [    35,  57000],
       [    36,  63000],
       [    42,  73000],
       [    43, 112000],
       [    45,  79000],
       [    46, 117000],
       [    58,  38000],
       [    48,  74000],
       [    37, 137000],
       [    37,  79000],
       [    40,  60000],
       [    42,  54000],
       [    51, 134000],
       [    47, 113000],
       [    36, 125000],
       [    38,  50000],
       [    42,  70000],
       [    39,  96000],
       [    38,  50000],
       [    49, 141000],
       [    39,  79000],
       [    39,  75000],
       [    54, 104000],
       [    35,  55000],
       [    45,  32000],
       [    36,  60000],
       [    52, 138000],
       [    53,  82000],
       [    41,  52000],
       [    48,  30000],
       [    48, 131000],
       [    41,  60000],
       [    41,  72000],
       [    42,  75000],
       [    36, 118000],
       [    47, 107000],
       [    38,  51000],
       [    48, 119000],
       [    42,  65000],
       [    40,  65000],
       [    57,  60000],
       [    36,  54000],
       [    58, 144000],
       [    35,  79000],
       [    38,  55000],
       [    39, 122000],
       [    53, 104000],
       [    35,  75000],
       [    38,  65000],
       [    47,  51000],
       [    47, 105000],
       [    41,  63000],
       [    53,  72000],
       [    54, 108000],
       [    39,  77000],
       [    38,  61000],
       [    38, 113000],
       [    37,  75000],
       [    42,  90000],
       [    37,  57000],
       [    36,  99000],
       [    60,  34000],
       [    54,  70000],
       [    41,  72000],
       [    40,  71000],
       [    42,  54000],
       [    43, 129000],
       [    53,  34000],
       [    47,  50000],
       [    42,  79000],
       [    42, 104000],
       [    59,  29000],
       [    58,  47000],
       [    46,  88000],
       [    38,  71000],
       [    54,  26000],
       [    60,  46000],
       [    60,  83000],
       [    39,  73000],
       [    59, 130000],
       [    37,  80000],
       [    46,  32000],
       [    46,  74000],
       [    42,  53000],
       [    41,  87000],
       [    58,  23000],
       [    42,  64000],
       [    48,  33000],
       [    44, 139000],
       [    49,  28000],
       [    57,  33000],
       [    56,  60000],
       [    49,  39000],
       [    39,  71000],
       [    47,  34000],
       [    48,  35000],
       [    48,  33000],
       [    47,  23000],
       [    45,  45000],
       [    60,  42000],
       [    39,  59000],
       [    46,  41000],
       [    51,  23000],
       [    50,  20000],
       [    36,  33000],
       [    49,  36000]], dtype=int64)

In [16]:
y=data.iloc[:,4].values

In [17]:
y=y.reshape(-1,1)

In [18]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1]], dtype=int64)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [21]:
X_train

array([[    40, 142000],
       [    45,  32000],
       [    22,  81000],
       [    37,  75000],
       [    35,  53000],
       [    39,  59000],
       [    33,  41000],
       [    47,  25000],
       [    36, 125000],
       [    31,  71000],
       [    42,  70000],
       [    43, 129000],
       [    19,  26000],
       [    37,  77000],
       [    23,  66000],
       [    39,  61000],
       [    37,  62000],
       [    40,  72000],
       [    35,  73000],
       [    19,  19000],
       [    32,  86000],
       [    18,  86000],
       [    30, 116000],
       [    59,  83000],
       [    35,  75000],
       [    35,  38000],
       [    58,  23000],
       [    36,  54000],
       [    41,  71000],
       [    42,  64000],
       [    24,  58000],
       [    23,  48000],
       [    25,  33000],
       [    37,  72000],
       [    47,  20000],
       [    27, 137000],
       [    46,  96000],
       [    47,  47000],
       [    49,  74000],
       [    42,  54000],
       [    36,  52000],
       [    34, 115000],
       [    34,  43000],
       [    48, 131000],
       [    39, 122000],
       [    48,  96000],
       [    59, 130000],
       [    48,  33000],
       [    35,  97000],
       [    42,  65000],
       [    35,  75000],
       [    55, 125000],
       [    35,  57000],
       [    49,  86000],
       [    46,  23000],
       [    26,  86000],
       [    53, 143000],
       [    57,  33000],
       [    32, 120000],
       [    31,  89000],
       [    38,  80000],
       [    33, 149000],
       [    49,  36000],
       [    49,  89000],
       [    26,  52000],
       [    56, 133000],
       [    41,  30000],
       [    36,  63000],
       [    26,  81000],
       [    38, 112000],
       [    28,  55000],
       [    43, 133000],
       [    27,  20000],
       [    33,  31000],
       [    51,  23000],
       [    37,  53000],
       [    28,  37000],
       [    46,  22000],
       [    45,  26000],
       [    30,  80000],
       [    22,  27000],
       [    31,  15000],
       [    40,  47000],
       [    37, 146000],
       [    40,  57000],
       [    46,  59000],
       [    41,  79000],
       [    26,  16000],
       [    50,  20000],
       [    29,  83000],
       [    60,  42000],
       [    27,  88000],
       [    47,  43000],
       [    28,  85000],
       [    48,  35000],
       [    50,  36000],
       [    29,  83000],
       [    53,  34000],
       [    41,  45000],
       [    45,  79000],
       [    35,  88000],
       [    48, 138000],
       [    45,  22000],
       [    59,  29000],
       [    43, 112000],
       [    35,  79000],
       [    29,  43000],
       [    33, 113000],
       [    21,  16000],
       [    38,  61000],
       [    46, 117000],
       [    31,  18000],
       [    21,  72000],
       [    49, 141000],
       [    33,  43000],
       [    27,  84000],
       [    42,  80000],
       [    26,  30000],
       [    35, 147000],
       [    42,  53000],
       [    22,  63000],
       [    24,  23000],
       [    26,  17000],
       [    28,  59000],
       [    38,  71000],
       [    47,  50000],
       [    58, 144000],
       [    28,  79000],
       [    44,  39000],
       [    60,  42000],
       [    60,  46000],
       [    35,  23000],
       [    33,  69000],
       [    25,  79000],
       [    45,  45000],
       [    44, 139000],
       [    39,  71000],
       [    60, 102000],
       [    29,  75000],
       [    20,  82000],
       [    54, 108000],
       [    33,  51000],
       [    47,  34000],
       [    35,  72000],
       [    59,  42000],
       [    59,  88000],
       [    24,  19000],
       [    34,  25000],
       [    47, 113000],
       [    29, 148000],
       [    19,  70000],
       [    37,  57000],
       [    26,  84000],
       [    48, 119000],
       [    40, 107000],
       [    60, 108000],
       [    48, 141000],
       [    49,  39000],
       [    40,  65000],
       [    20,  36000],
       [    40,  75000],
       [    35,  50000],
       [    25,  22000],
       [    26,  80000],
       [    34,  43000],
       [    25,  80000],
       [    55,  39000],
       [    29,  28000],
       [    32, 100000],
       [    27,  31000],
       [    40,  60000],
       [    40,  61000],
       [    53, 104000],
       [    26,  72000],
       [    37,  55000],
       [    37, 144000],
       [    35,  55000],
       [    47,  23000],
       [    35,  47000],
       [    52,  38000],
       [    58,  38000],
       [    40,  57000],
       [    21,  88000],
       [    46,  28000],
       [    54, 104000],
       [    30,  89000],
       [    26, 118000],
       [    38, 113000],
       [    27,  58000],
       [    42, 104000],
       [    46,  41000],
       [    54,  26000],
       [    28,  87000],
       [    33,  60000],
       [    58,  47000],
       [    30, 107000],
       [    28,  59000],
       [    18,  44000],
       [    29,  61000],
       [    38,  71000],
       [    41,  60000],
       [    41,  59000],
       [    42,  79000],
       [    27,  58000],
       [    41,  51000],
       [    35,  50000],
       [    20,  23000],
       [    38,  65000],
       [    49,  28000],
       [    35,  27000],
       [    33,  28000],
       [    47, 107000],
       [    37,  80000],
       [    58, 101000],
       [    28,  84000],
       [    23,  28000],
       [    31,  66000],
       [    21,  68000],
       [    57, 122000],
       [    26,  32000],
       [    32, 117000],
       [    59, 143000],
       [    52,  90000],
       [    28, 123000],
       [    42,  65000],
       [    38,  50000],
       [    35,  91000],
       [    31,  68000],
       [    40,  59000],
       [    36, 144000],
       [    20,  82000],
       [    47,  30000],
       [    32,  18000],
       [    35,  20000],
       [    40,  75000],
       [    35,  44000],
       [    46,  74000],
       [    31,  34000],
       [    48,  90000],
       [    59,  76000],
       [    42,  73000],
       [    46,  32000],
       [    18,  68000],
       [    39, 134000],
       [    19,  85000],
       [    52, 150000],
       [    38,  51000],
       [    30, 135000],
       [    42,  90000],
       [    52, 114000],
       [    35, 108000],
       [    35,  77000],
       [    27,  54000],
       [    30,  79000],
       [    56, 104000],
       [    45,  22000],
       [    42,  54000],
       [    41,  80000],
       [    46,  79000],
       [    41,  87000],
       [    37,  74000],
       [    51, 146000],
       [    35,  72000],
       [    31,  74000],
       [    41,  72000],
       [    38,  59000],
       [    31,  76000],
       [    60,  83000],
       [    39,  96000],
       [    49,  65000],
       [    46,  82000],
       [    30,  49000],
       [    30,  17000],
       [    35,  61000],
       [    37,  70000],
       [    36,  60000],
       [    27,  57000],
       [    26,  80000],
       [    49,  28000],
       [    37,  52000],
       [    39,  77000],
       [    19,  21000],
       [    22,  55000],
       [    37,  33000],
       [    32, 135000],
       [    40,  57000],
       [    38,  50000],
       [    39,  71000],
       [    36, 118000],
       [    57,  60000],
       [    56,  60000],
       [    36,  33000],
       [    50,  88000],
       [    49,  88000],
       [    20,  49000],
       [    54,  70000],
       [    60,  34000],
       [    24,  55000],
       [    23,  20000],
       [    38,  55000],
       [    39,  75000],
       [    41,  72000],
       [    31, 118000],
       [    31,  58000],
       [    37,  79000],
       [    24,  27000],
       [    48,  33000],
       [    24,  89000],
       [    30,  87000],
       [    47,  51000],
       [    22,  18000],
       [    39,  73000],
       [    24,  84000],
       [    34,  72000],
       [    37,  93000],
       [    32, 117000],
       [    29,  43000],
       [    48, 134000],
       [    58,  95000],
       [    20,  74000]], dtype=int64)

In [22]:
X_test

array([[    39, 134000],
       [    26,  15000],
       [    40,  71000],
       [    26,  35000],
       [    35,  25000],
       [    24,  32000],
       [    57,  74000],
       [    32, 150000],
       [    35,  39000],
       [    27,  89000],
       [    25,  87000],
       [    28,  89000],
       [    19,  76000],
       [    48,  29000],
       [    36, 126000],
       [    35,  22000],
       [    55, 130000],
       [    37,  80000],
       [    40,  78000],
       [    47, 105000],
       [    47,  49000],
       [    27,  96000],
       [    23,  63000],
       [    19,  25000],
       [    28,  32000],
       [    42,  75000],
       [    35,  71000],
       [    24,  55000],
       [    37,  78000],
       [    51, 134000],
       [    37,  71000],
       [    41,  72000],
       [    23,  82000],
       [    34, 112000],
       [    28,  44000],
       [    35,  60000],
       [    35,  58000],
       [    45, 131000],
       [    39,  79000],
       [    37, 137000],
       [    36,  99000],
       [    42, 108000],
       [    52, 138000],
       [    39, 106000],
       [    18,  52000],
       [    25,  90000],
       [    20,  86000],
       [    26,  15000],
       [    41,  72000],
       [    39,  42000],
       [    42, 149000],
       [    29,  47000],
       [    27,  90000],
       [    46,  88000],
       [    27,  17000],
       [    26,  43000],
       [    18,  82000],
       [    35,  59000],
       [    48,  30000],
       [    53,  72000],
       [    41,  52000],
       [    48,  41000],
       [    30,  15000],
       [    47, 144000],
       [    36,  75000],
       [    36,  50000],
       [    32,  18000],
       [    42,  80000],
       [    38,  61000],
       [    39,  42000],
       [    35,  65000],
       [    50,  44000],
       [    52,  21000],
       [    57,  26000],
       [    53,  82000],
       [    48,  74000],
       [    29,  80000],
       [    41,  52000],
       [    30,  62000],
       [    41,  63000]], dtype=int64)

In [23]:
y_train

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0]], dtype=int64)

In [24]:
y_test

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
SC=StandardScaler()

In [27]:
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

C:\Users\ssn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [28]:
X_train

array([[ 0.19152488,  2.14257431],
       [ 0.66297073, -1.11033127],
       [-1.5056802 ,  0.33869031],
       [-0.09134263,  0.1612591 ],
       [-0.27992098, -0.48932202],
       [ 0.09723571, -0.3118908 ],
       [-0.46849932, -0.84418445],
       [ 0.85154908, -1.31733435],
       [-0.18563181,  1.63985254],
       [-0.65707766,  0.04297162],
       [ 0.38010322,  0.01339975],
       [ 0.47439239,  1.75814002],
       [-1.78854772, -1.28776248],
       [-0.09134263,  0.22040284],
       [-1.41139103, -0.10488772],
       [ 0.09723571, -0.25274707],
       [-0.09134263, -0.2231752 ],
       [ 0.19152488,  0.07254349],
       [-0.27992098,  0.10211536],
       [-1.78854772, -1.49476556],
       [-0.56278849,  0.48654966],
       [-1.88283689,  0.48654966],
       [-0.75136683,  1.37370572],
       [ 1.98301913,  0.39783405],
       [-0.27992098,  0.1612591 ],
       [-0.27992098, -0.93290005],
       [ 1.88872996, -1.37647809],
       [-0.18563181, -0.45975015],
       [ 0.28581405,  0.04297162],
       [ 0.38010322, -0.16403146],
       [-1.31710186, -0.34146267],
       [-1.41139103, -0.63718136],
       [-1.22281269, -1.0807594 ],
       [-0.09134263,  0.07254349],
       [ 0.85154908, -1.46519369],
       [-1.03423435,  1.99471497],
       [ 0.75725991,  0.78226834],
       [ 0.85154908, -0.66675323],
       [ 1.04012742,  0.13168723],
       [ 0.38010322, -0.45975015],
       [-0.18563181, -0.51889389],
       [-0.37421015,  1.34413385],
       [-0.37421015, -0.78504071],
       [ 0.94583825,  1.81728376],
       [ 0.09723571,  1.55113694],
       [ 0.94583825,  0.78226834],
       [ 1.98301913,  1.78771189],
       [ 0.94583825, -1.0807594 ],
       [-0.27992098,  0.81184021],
       [ 0.38010322, -0.13445959],
       [-0.27992098,  0.1612591 ],
       [ 1.60586245,  1.63985254],
       [-0.27992098, -0.37103454],
       [ 1.04012742,  0.48654966],
       [ 0.75725991, -1.37647809],
       [-1.12852352,  0.48654966],
       [ 1.4172841 ,  2.17214618],
       [ 1.79444079, -1.0807594 ],
       [-0.56278849,  1.4919932 ],
       [-0.65707766,  0.57526526],
       [ 0.00294654,  0.30911844],
       [-0.46849932,  2.3495774 ],
       [ 1.04012742, -0.99204379],
       [ 1.04012742,  0.57526526],
       [-1.12852352, -0.51889389],
       [ 1.70015162,  1.87642749],
       [ 0.28581405, -1.169475  ],
       [-0.18563181, -0.19360333],
       [-1.12852352,  0.33869031],
       [ 0.00294654,  1.25541825],
       [-0.93994518, -0.43017828],
       [ 0.47439239,  1.87642749],
       [-1.03423435, -1.46519369],
       [-0.46849932, -1.13990313],
       [ 1.22870576, -1.37647809],
       [-0.09134263, -0.48932202],
       [-0.93994518, -0.96247192],
       [ 0.75725991, -1.40604995],
       [ 0.66297073, -1.28776248],
       [-0.75136683,  0.30911844],
       [-1.5056802 , -1.25819061],
       [-0.65707766, -1.61305304],
       [ 0.19152488, -0.66675323],
       [-0.09134263,  2.26086179],
       [ 0.19152488, -0.37103454],
       [ 0.75725991, -0.3118908 ],
       [ 0.28581405,  0.27954657],
       [-1.12852352, -1.58348117],
       [ 1.13441659, -1.46519369],
       [-0.845656  ,  0.39783405],
       [ 2.0773083 , -0.81461258],
       [-1.03423435,  0.54569339],
       [ 0.85154908, -0.78504071],
       [-0.93994518,  0.45697779],
       [ 0.94583825, -1.02161566],
       [ 1.13441659, -0.99204379],
       [-0.845656  ,  0.39783405],
       [ 1.4172841 , -1.05118753],
       [ 0.28581405, -0.72589697],
       [ 0.66297073,  0.27954657],
       [-0.27992098,  0.54569339],
       [ 0.94583825,  2.02428684],
       [ 0.66297073, -1.40604995],
       [ 1.98301913, -1.19904687],
       [ 0.47439239,  1.25541825],
       [-0.27992098,  0.27954657],
       [-0.845656  , -0.78504071],
       [-0.46849932,  1.28499012],
       [-1.59996937, -1.58348117],
       [ 0.00294654, -0.25274707],
       [ 0.75725991,  1.40327759],
       [-0.65707766, -1.52433743],
       [-1.59996937,  0.07254349],
       [ 1.04012742,  2.11300245],
       [-0.46849932, -0.78504071],
       [-1.03423435,  0.42740592],
       [ 0.38010322,  0.30911844],
       [-1.12852352, -1.169475  ],
       [-0.27992098,  2.29043366],
       [ 0.38010322, -0.48932202],
       [-1.5056802 , -0.19360333],
       [-1.31710186, -1.37647809],
       [-1.12852352, -1.5539093 ],
       [-0.93994518, -0.3118908 ],
       [ 0.00294654,  0.04297162],
       [ 0.85154908, -0.57803762],
       [ 1.88872996,  2.20171805],
       [-0.93994518,  0.27954657],
       [ 0.56868156, -0.90332818],
       [ 2.0773083 , -0.81461258],
       [ 2.0773083 , -0.6963251 ],
       [-0.27992098, -1.37647809],
       [-0.46849932, -0.01617212],
       [-1.22281269,  0.27954657],
       [ 0.66297073, -0.72589697],
       [ 0.56868156,  2.05385871],
       [ 0.09723571,  0.04297162],
       [ 2.0773083 ,  0.95969956],
       [-0.845656  ,  0.1612591 ],
       [-1.69425854,  0.36826218],
       [ 1.51157328,  1.13713077],
       [-0.46849932, -0.54846576],
       [ 0.85154908, -1.05118753],
       [-0.27992098,  0.07254349],
       [ 1.98301913, -0.81461258],
       [ 1.98301913,  0.54569339],
       [-1.31710186, -1.49476556],
       [-0.37421015, -1.31733435],
       [ 0.85154908,  1.28499012],
       [-0.845656  ,  2.32000553],
       [-1.78854772,  0.01339975],
       [-0.09134263, -0.37103454],
       [-1.12852352,  0.42740592],
       [ 0.94583825,  1.46242133],
       [ 0.19152488,  1.1075589 ],
       [ 2.0773083 ,  1.13713077],
       [ 0.94583825,  2.11300245],
       [ 1.04012742, -0.90332818],
       [ 0.19152488, -0.13445959],
       [-1.69425854, -0.99204379],
       [ 0.19152488,  0.1612591 ],
       [-0.27992098, -0.57803762],
       [-1.22281269, -1.40604995],
       [-1.12852352,  0.30911844],
       [-0.37421015, -0.78504071],
       [-1.22281269,  0.30911844],
       [ 1.60586245, -0.90332818],
       [-0.845656  , -1.22861874],
       [-0.56278849,  0.90055582],
       [-1.03423435, -1.13990313],
       [ 0.19152488, -0.28231894],
       [ 0.19152488, -0.25274707],
       [ 1.4172841 ,  1.0188433 ],
       [-1.12852352,  0.07254349],
       [-0.09134263, -0.43017828],
       [-0.09134263,  2.20171805],
       [-0.27992098, -0.43017828],
       [ 0.85154908, -1.37647809],
       [-0.27992098, -0.66675323],
       [ 1.32299493, -0.93290005],
       [ 1.88872996, -0.93290005],
       [ 0.19152488, -0.37103454],
       [-1.59996937,  0.54569339],
       [ 0.75725991, -1.22861874],
       [ 1.51157328,  1.0188433 ],
       [-0.75136683,  0.57526526],
       [-1.12852352,  1.43284946],
       [ 0.00294654,  1.28499012],
       [-1.03423435, -0.34146267],
       [ 0.38010322,  1.0188433 ],
       [ 0.75725991, -0.84418445],
       [ 1.51157328, -1.28776248],
       [-0.93994518,  0.51612152],
       [-0.46849932, -0.28231894],
       [ 1.88872996, -0.66675323],
       [-0.75136683,  1.1075589 ],
       [-0.93994518, -0.3118908 ],
       [-1.88283689, -0.75546884],
       [-0.845656  , -0.25274707],
       [ 0.00294654,  0.04297162],
       [ 0.28581405, -0.28231894],
       [ 0.28581405, -0.3118908 ],
       [ 0.38010322,  0.27954657],
       [-1.03423435, -0.34146267],
       [ 0.28581405, -0.54846576],
       [-0.27992098, -0.57803762],
       [-1.69425854, -1.37647809],
       [ 0.00294654, -0.13445959],
       [ 1.04012742, -1.22861874],
       [-0.27992098, -1.25819061],
       [-0.46849932, -1.22861874],
       [ 0.85154908,  1.1075589 ],
       [-0.09134263,  0.30911844],
       [ 1.88872996,  0.93012769],
       [-0.93994518,  0.42740592],
       [-1.41139103, -1.22861874],
       [-0.65707766, -0.10488772],
       [-1.59996937, -0.04574398],
       [ 1.79444079,  1.55113694],
       [-1.12852352, -1.11033127],
       [-0.56278849,  1.40327759],
       [ 1.98301913,  2.17214618],
       [ 1.32299493,  0.60483713],
       [-0.93994518,  1.5807088 ],
       [ 0.38010322, -0.13445959],
       [ 0.00294654, -0.57803762],
       [-0.27992098,  0.634409  ],
       [-0.65707766, -0.04574398],
       [ 0.19152488, -0.3118908 ],
       [-0.18563181,  2.20171805],
       [-1.69425854,  0.36826218],
       [ 0.85154908, -1.169475  ],
       [-0.56278849, -1.52433743],
       [-0.27992098, -1.46519369],
       [ 0.19152488,  0.1612591 ],
       [-0.27992098, -0.75546884],
       [ 0.75725991,  0.13168723],
       [-0.65707766, -1.05118753],
       [ 0.94583825,  0.60483713],
       [ 1.98301913,  0.19083097],
       [ 0.38010322,  0.10211536],
       [ 0.75725991, -1.11033127],
       [-1.88283689, -0.04574398],
       [ 0.09723571,  1.90599936],
       [-1.78854772,  0.45697779],
       [ 1.32299493,  2.37914927],
       [ 0.00294654, -0.54846576],
       [-0.75136683,  1.93557123],
       [ 0.38010322,  0.60483713],
       [ 1.32299493,  1.31456198],
       [-0.27992098,  1.13713077],
       [-0.27992098,  0.22040284],
       [-1.03423435, -0.45975015],
       [-0.75136683,  0.27954657],
       [ 1.70015162,  1.0188433 ],
       [ 0.66297073, -1.40604995],
       [ 0.38010322, -0.45975015],
       [ 0.28581405,  0.30911844],
       [ 0.75725991,  0.27954657],
       [ 0.28581405,  0.51612152],
       [-0.09134263,  0.13168723],
       [ 1.22870576,  2.26086179],
       [-0.27992098,  0.07254349],
       [-0.65707766,  0.13168723],
       [ 0.28581405,  0.07254349],
       [ 0.00294654, -0.3118908 ],
       [-0.65707766,  0.19083097],
       [ 2.0773083 ,  0.39783405],
       [ 0.09723571,  0.78226834],
       [ 1.04012742, -0.13445959],
       [ 0.75725991,  0.36826218],
       [-0.75136683, -0.60760949],
       [-0.75136683, -1.5539093 ],
       [-0.27992098, -0.25274707],
       [-0.09134263,  0.01339975],
       [-0.18563181, -0.28231894],
       [-1.03423435, -0.37103454],
       [-1.12852352,  0.30911844],
       [ 1.04012742, -1.22861874],
       [-0.09134263, -0.51889389],
       [ 0.09723571,  0.22040284],
       [-1.78854772, -1.43562182],
       [-1.5056802 , -0.43017828],
       [-0.09134263, -1.0807594 ],
       [-0.56278849,  1.93557123],
       [ 0.19152488, -0.37103454],
       [ 0.00294654, -0.57803762],
       [ 0.09723571,  0.04297162],
       [-0.18563181,  1.43284946],
       [ 1.79444079, -0.28231894],
       [ 1.70015162, -0.28231894],
       [-0.18563181, -1.0807594 ],
       [ 1.13441659,  0.54569339],
       [ 1.04012742,  0.54569339],
       [-1.69425854, -0.60760949],
       [ 1.51157328,  0.01339975],
       [ 2.0773083 , -1.05118753],
       [-1.31710186, -0.43017828],
       [-1.41139103, -1.46519369],
       [ 0.00294654, -0.43017828],
       [ 0.09723571,  0.1612591 ],
       [ 0.28581405,  0.07254349],
       [-0.65707766,  1.43284946],
       [-0.65707766, -0.34146267],
       [-0.09134263,  0.27954657],
       [-1.31710186, -1.25819061],
       [ 0.94583825, -1.0807594 ],
       [-1.31710186,  0.57526526],
       [-0.75136683,  0.51612152],
       [ 0.85154908, -0.54846576],
       [-1.5056802 , -1.52433743],
       [ 0.09723571,  0.10211536],
       [-1.31710186,  0.42740592],
       [-0.37421015,  0.07254349],
       [-0.09134263,  0.69355274],
       [-0.56278849,  1.40327759],
       [-0.845656  , -0.78504071],
       [ 0.94583825,  1.90599936],
       [ 1.88872996,  0.75269648],
       [-1.69425854,  0.13168723]])

In [29]:
X_test

array([[ 0.09723571,  1.90599936],
       [-1.12852352, -1.61305304],
       [ 0.19152488,  0.04297162],
       [-1.12852352, -1.02161566],
       [-0.27992098, -1.31733435],
       [-1.31710186, -1.11033127],
       [ 1.79444079,  0.13168723],
       [-0.56278849,  2.37914927],
       [-0.27992098, -0.90332818],
       [-1.03423435,  0.57526526],
       [-1.22281269,  0.51612152],
       [-0.93994518,  0.57526526],
       [-1.78854772,  0.19083097],
       [ 0.94583825, -1.19904687],
       [-0.18563181,  1.66942441],
       [-0.27992098, -1.40604995],
       [ 1.60586245,  1.78771189],
       [-0.09134263,  0.30911844],
       [ 0.19152488,  0.2499747 ],
       [ 0.85154908,  1.04841516],
       [ 0.85154908, -0.60760949],
       [-1.03423435,  0.78226834],
       [-1.41139103, -0.19360333],
       [-1.78854772, -1.31733435],
       [-0.93994518, -1.11033127],
       [ 0.38010322,  0.1612591 ],
       [-0.27992098,  0.04297162],
       [-1.31710186, -0.43017828],
       [-0.09134263,  0.2499747 ],
       [ 1.22870576,  1.90599936],
       [-0.09134263,  0.04297162],
       [ 0.28581405,  0.07254349],
       [-1.41139103,  0.36826218],
       [-0.37421015,  1.25541825],
       [-0.93994518, -0.75546884],
       [-0.27992098, -0.28231894],
       [-0.27992098, -0.34146267],
       [ 0.66297073,  1.81728376],
       [ 0.09723571,  0.27954657],
       [-0.09134263,  1.99471497],
       [-0.18563181,  0.87098395],
       [ 0.38010322,  1.13713077],
       [ 1.32299493,  2.02428684],
       [ 0.09723571,  1.07798703],
       [-1.88283689, -0.51889389],
       [-1.22281269,  0.60483713],
       [-1.69425854,  0.48654966],
       [-1.12852352, -1.61305304],
       [ 0.28581405,  0.07254349],
       [ 0.09723571, -0.81461258],
       [ 0.38010322,  2.3495774 ],
       [-0.845656  , -0.66675323],
       [-1.03423435,  0.60483713],
       [ 0.75725991,  0.54569339],
       [-1.03423435, -1.5539093 ],
       [-1.12852352, -0.78504071],
       [-1.88283689,  0.36826218],
       [-0.27992098, -0.3118908 ],
       [ 0.94583825, -1.169475  ],
       [ 1.4172841 ,  0.07254349],
       [ 0.28581405, -0.51889389],
       [ 0.94583825, -0.84418445],
       [-0.75136683, -1.61305304],
       [ 0.85154908,  2.20171805],
       [-0.18563181,  0.1612591 ],
       [-0.18563181, -0.57803762],
       [-0.56278849, -1.52433743],
       [ 0.38010322,  0.30911844],
       [ 0.00294654, -0.25274707],
       [ 0.09723571, -0.81461258],
       [-0.27992098, -0.13445959],
       [ 1.13441659, -0.75546884],
       [ 1.32299493, -1.43562182],
       [ 1.79444079, -1.28776248],
       [ 1.4172841 ,  0.36826218],
       [ 0.94583825,  0.13168723],
       [-0.845656  ,  0.30911844],
       [ 0.28581405, -0.51889389],
       [-0.75136683, -0.2231752 ],
       [ 0.28581405, -0.19360333]])

In [30]:
from sklearn.svm import SVC

In [31]:
classifier =SVC(kernel='linear')
classifier.fit(X_train,y_train)

C:\Users\ssn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
classifier =SVC(kernel='linear')
classifier.fit(X_train,y_train.ravel())

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [33]:
y_predictor=classifier.predict(X_test)

In [34]:
y_predictor

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [35]:
from sklearn.metrics import confusion_matrix
error_predictions=confusion_matrix(y_test,y_predictor)

In [38]:
error_predictions

array([[49,  3],
       [ 9, 19]], dtype=int64)